version: '3.8'

services:
  frontend:
    build: .
    container_name: mindflow-frontend
    ports:
      - "8081:8080"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:5000/api
    depends_on:
      - backend

  backend:
    build: ./backend
    container_name: mindflow-backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - PORT=5000
      - MONGODB_URI=mongodb+srv://raphsant20:bCU4Oz6z7qJP0oBZ@cluster0.up35ing.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0